### ISSUE TITLE
Phlex isn't in beta yet

### ISSUE THREAD

**Issue by joeldrapper** [mfornaciari/delivery-app#29]
Hey, I noticed you added `phlex` to your Gemfile. I wanted to let you know Phlex isn't in beta quite yet, we've only pushed to RubyGems once to reserve the name. In the meantime, you can install Phlex edge directly from GitHub.

```ruby
gem "phlex", github: "joeldrapper/phlex"
```

**Comment by mfornaciari** [comment]
Hey, thanks for letting me know! I thought it was interesting and was planning on fiddling around with it a little, but I guess I'll wait for the beta, then. I haven't actually used it in the project yet, so I went ahead and removed it from the Gemfile for now.
